---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-volume-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-db
spec:
  selector:
    matchLabels:
      app: todo-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: todo-db
    spec:
      containers:
      - image: cloudacode/mariadb-todo:v1.0.1
        name: todo-db
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: 1Gi
            memory: 512Mi
          requests:
            cpu: 250m
            ephemeral-storage: 1Gi
            memory: 512Mi
        ports:
        - containerPort: 3306
          name: todo-db
        volumeMounts:
        - name: todo-volume
          mountPath: /var/lib/mysql
      volumes:
      - name: todo-volume
        persistentVolumeClaim:
          claimName: todo-volume-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: todo-db
spec:
  ports:
  - port: 3306
  selector:
    app: todo-db
  clusterIP: None
