# Custom error page configMap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-error-pages
data:
  404: |
    <!DOCTYPE html>
    <html>
      <head><title>404 PAGE NOT FOUND</title></head>
      <body>404 PAGE NOT FOUND</body>
    </html>
  503: |
    <!DOCTYPE html>
    <html>
      <head><title>503 CUSTOM SERVICE UNAVAILABLE</title></head>
      <body>503 CUSTOM SERVICE UNAVAILABLE</body>
    </html>