# Project information
site_name: cloudacode - coolstuff
site_url: https://cloudacode.github.io/coolstuff/
site_author: KC Chang

# Repository
repo_name: cloudacode/coolstuff
repo_url: https://github.com/cloudacode/coolstuff
edit_uri: ""

# Configuration
theme:
  name: material

# Page tree
nav:
  - Home: index.md
